### ISSUE TITLE
复现效果不如论文

### ISSUE THREAD

**Issue by Zhaozixiang1228** [hli1221/densefuse-pytorch#1]
李博您好，麻烦问您一下，为什么pytorch版本的预训练权重相较论文中的结果差距较大，我根据您文章中的参数进行训练，与预训练权重得到的结果较为接近，但是均大幅度低于文章中的参数，请李师兄为我指点迷津，谢谢！

**Comment by Dandelion111** [comment]
你好，我想请问一下pytorch_msssim中第36行代码(_, channel, height, width) = img1.size()
其中img1.size()为什么要返回四个参数，它不应该是1*256*256吗？

**Comment by hli1221** [comment]
> 李博您好，麻烦问您一下，为什么pytorch版本的预训练权重相较论文中的结果差距较大，我根据您文章中的参数进行训练，与预训练权重得到的结果较为接近，但是均大幅度低于文章中的参数，请李师兄为我指点迷津，谢谢！

你好，感谢你对我们的工作感兴趣。目前pytorch版本只是实现了相应的功能，对性能没有做验证。若想做对比，建议使用tensflow版本的代码。

**Comment by hli1221** [comment]
> 你好，我想请问一下pytorch_msssim中第36行代码(_, channel, height, width) = img1.size()
> 其中img1.size()为什么要返回四个参数，它不应该是1_256_256吗？

你好，img1应该是一个tensor类型数据，其返回的就是四个参数 (B, C, H, W)，第一个参数是指batch size

**Comment by Dandelion111** [comment]
没想到还能得到本尊的回复，这个img1是outputs中的一个output，就是一张图片，我用debug功能也查看了，是1 256 256，但是那一行代码需要返回四个参数，还有一个疑问就是计算欧式距离的时候，为啥一个是1 256 256 的tensor和4 1 256 256的tensor，就是用一张图的输出和一个batchsize一起计算，谢谢李师兄

**Comment by Zhaozixiang1228** [comment]
> 没想到还能得到本尊的回复，这个img1是outputs中的一个output，就是一张图片，我用debug功能也查看了，是1 256 256，但是那一行代码需要返回四个参数，还有一个疑问就是计算欧式距离的时候，为啥一个是1 256 256 的tensor和4 1 256 256的tensor，就是用一张图的输出和一个batchsize一起计算，谢谢李师兄

兄弟，对于第一个问题，你把它reshape一下就行；对于第二个问题，他是batch中每一张图都和ground truth比一下，最后再加起来，所以是写在循环里的。这样完成了一个minibatch的loss计算。

**Comment by hli1221** [comment]
> 没想到还能得到本尊的回复，这个img1是outputs中的一个output，就是一张图片，我用debug功能也查看了，是1 256 256，但是那一行代码需要返回四个参数，还有一个疑问就是计算欧式距离的时候，为啥一个是1 256 256 的tensor和4 1 256 256的tensor，就是用一张图的输出和一个batchsize一起计算，谢谢李师兄

你好。在训练阶段和测试阶段output的类型和输出是不一样的。pytorch_msssim这个函数只会在训练阶段用到，在训练阶段output是tensor。在测试阶段由于output要保存到本地，所以做了类型转换和reshape。这些可能需要你再看看代码。

**Comment by hli1221** [comment]
> > 没想到还能得到本尊的回复，这个img1是outputs中的一个output，就是一张图片，我用debug功能也查看了，是1 256 256，但是那一行代码需要返回四个参数，还有一个疑问就是计算欧式距离的时候，为啥一个是1 256 256 的tensor和4 1 256 256的tensor，就是用一张图的输出和一个batchsize一起计算，谢谢李师兄
> 
> 兄弟，对于第一个问题，你把它reshape一下就行；对于第二个问题，他是batch中每一张图都和ground truth比一下，最后再加起来，所以是写在循环里的。这样完成了一个minibatch的loss计算。

感谢你的回复。

**Comment by Zhaozixiang1228** [comment]
> > > 没想到还能得到本尊的回复，这个img1是outputs中的一个output，就是一张图片，我用debug功能也查看了，是1 256 256，但是那一行代码需要返回四个参数，还有一个疑问就是计算欧式距离的时候，为啥一个是1 256 256 的tensor和4 1 256 256的tensor，就是用一张图的输出和一个batchsize一起计算，谢谢李师兄
> > 
> > 
> > 兄弟，对于第一个问题，你把它reshape一下就行；对于第二个问题，他是batch中每一张图都和ground truth比一下，最后再加起来，所以是写在循环里的。这样完成了一个minibatch的loss计算。
> 
> 感谢你的回复。

感谢李博的鼓励，我最近有两篇引用李博这个工作的文章，但愿运气好点可以中吧hhhhh

**Comment by hli1221** [comment]
> > > > 没想到还能得到本尊的回复，这个img1是outputs中的一个output，就是一张图片，我用debug功能也查看了，是1 256 256，但是那一行代码需要返回四个参数，还有一个疑问就是计算欧式距离的时候，为啥一个是1 256 256 的tensor和4 1 256 256的tensor，就是用一张图的输出和一个batchsize一起计算，谢谢李师兄
> > > 
> > > 
> > > 兄弟，对于第一个问题，你把它reshape一下就行；对于第二个问题，他是batch中每一张图都和ground truth比一下，最后再加起来，所以是写在循环里的。这样完成了一个minibatch的loss计算。
> > 
> > 
> > 感谢你的回复。
> 
> 感谢李博的鼓励，我最近有两篇引用李博这个工作的文章，但愿运气好点可以中吧hhhhh

应该没问题的。祝你好运

**Comment by hli1221** [comment]
@Dandelion111 
你好，最近也有其他人反应了类似问题。我复查了代码，发现在 ‘net.py’ 文件中第102行代码有问题。我已经对代码进行了更新。请重新下载最新版本，应该能够解决你的问题

**Comment by Dandelion111** [comment]
好的，感谢李师兄！
